all:
	make -C flocq
	make -C ia32
	make -C lib
	make -C old
	make -C common
	make -C backend

clean:
	make -C flocq clean
	make -C ia32 clean
	make -C lib clean
	make -C old clean
	make -C common clean
	make -C backend clean
